name : SMU BIA
description : SMU Business Intelligence & Analytics
keyword : smu, business intelligence, analytics, data science, co-learning, data projects
url : http://www.smubia.org
email : limkopi@smubia.org
twitter : smubia
github : smubia
author : Gabriel Chuan
year : 2017
markdown : kramdown
exclude :
  - node_modules
mainpages:
  - url: /about
    title: About